baseurl: ""
url: https://blog.kssim.com
enforce_ssl: blog.kssim.com

theme_settings:
  title: KYEONG-SEOB SIM
  avatar: assets/img/default/profile.jpg
  favicon: assets/favicon.ico
  description: "KyeongSeob Sim"

  header_text:
  header_text_feature_image: assets/img/default/main.jpg
  footer_text: © 2018 Kyeong-Seob Sim

  rss: true
  email_address: ksub0912@gmail.com
  profile: https://profile.kssim.com
  github: kssim
  slideshare: https://www.slideshare.net/ssuser674248 

  google_analytics: UA-116951375-3
  katex: true
  search: true
  tags: true

  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  post_navigation: true

paginate: 5
paginate_path: "blog/page:num"

markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
exclude: ["Gemfile", "Gemfile.lock", "*.gem", "LICENSE", "README.md"]
