baseurl: ""
url: https://blog.kssim.com
enforce_ssl: blog.kssim.com

theme_settings:
  title: KYEONG-SEOB SIM
  avatar: assets/img/default/profile.jpg
  favicon: assets/favicon.ico
  description: "KyeongSeob Sim"

  header_text:
  header_text_feature_image: assets/img/default/main.jpg
  footer_text: © Kyeong-Seob Sim / All rights reserved. Since 2018

  rss: true
  email_address: ksub0912@gmail.com
  github: "kssim"
  linkedin: https://linkedin.com/in/kssim

  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  katex: true # Enable if using math markup
  search: true
  tags: true

  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  post_navigation: true

paginate: 5
paginate_path: "blog/page:num"

markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
exclude: ["Gemfile", "Gemfile.lock", "*.gem", "LICENSE", "README.md"]
